# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('appointmentManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
